// licence-client for __PRODUCT__ — generated by Helm's licence manager.
// Single file, zero dependencies (Ed25519 verify is bundled in). Drop into the
// app, then:
//
//   import { verifyLicence } from './licence-client.js';
//   const r = await verifyLicence(userPastedKey);
//   if (!r.valid) showLicenceScreen(r.reason);   // reasons below
//
// Checks (offline, no network): signature → product → expiry. Then, when
// online, a best-effort revocation check: fetches the signed public list at
// most once per 24 h with a 3 s timeout; unreachable ⇒ last cached list;
// never fetched ⇒ allowed. reasons: missing | malformed | bad-signature |
// wrong-product | expired | revoked | null (valid).
import { verifyAsync } from '@noble/ed25519';

const PUBLIC_KEY = '__PUBLIC_KEY__';
const PRODUCT = '__PRODUCT__';
const REVOKED_URL = '__REVOKED_URL__';

const KEY_PREFIX = 'IPL1';
const REVOCATION_PREFIX = 'IPLR1';
const CACHE_KEY = 'ipl-revoked:' + PRODUCT;
const FETCH_INTERVAL_MS = 24 * 60 * 60 * 1000;
const FETCH_TIMEOUT_MS = 3000;

const ENC = new TextEncoder();

function base64urlToBytes(str) {
  const b64 = str.replace(/-/g, '+').replace(/_/g, '/');
  const bin = atob(b64); // throws on malformed input — callers guard
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function hexToBytes(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function parseToken(str, prefix) {
  if (typeof str !== 'string' || str.trim() === '') return { ok: false, reason: 'missing' };
  const parts = str.trim().split('.');
  if (parts.length !== 3 || parts[0] !== prefix) return { ok: false, reason: 'malformed' };
  let payload, sigBytes;
  try {
    payload = JSON.parse(new TextDecoder().decode(base64urlToBytes(parts[1])));
    sigBytes = base64urlToBytes(parts[2]);
  } catch {
    return { ok: false, reason: 'malformed' };
  }
  if (sigBytes.length !== 64 || !payload || typeof payload !== 'object') {
    return { ok: false, reason: 'malformed' };
  }
  return { ok: true, payload, payloadSegment: parts[1], sigBytes };
}

async function sigValid(payloadSegment, sigBytes) {
  try {
    return await verifyAsync(sigBytes, ENC.encode(payloadSegment), hexToBytes(PUBLIC_KEY));
  } catch {
    return false;
  }
}

// Best-effort revocation list: only a successfully fetched AND signature-valid
// list ever updates the cache, so a tampered host cannot poison it.
async function revokedJtis({ now, fetchImpl, storage }) {
  const store = storage || (typeof localStorage !== 'undefined' ? localStorage : null);
  const doFetch = fetchImpl || (typeof fetch !== 'undefined' ? fetch : null);
  let cached = null;
  try { cached = JSON.parse((store && store.getItem(CACHE_KEY)) || 'null'); } catch { cached = null; }

  if (doFetch && (!cached || now - cached.fetchedAt > FETCH_INTERVAL_MS)) {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await doFetch(REVOKED_URL, { signal: ctrl.signal });
      const body = await res.json(); // { token: "IPLR1..." }
      const parsed = parseToken(body.token, REVOCATION_PREFIX);
      // Monotonicity: a validly signed but OLDER list (stale host/CDN) never
      // replaces a newer cached one — it could transiently un-revoke a key.
      const newer = !cached || !cached.updated || !parsed.ok
        || Date.parse(parsed.payload.updated) >= Date.parse(cached.updated);
      if (parsed.ok && newer && Array.isArray(parsed.payload.revoked) &&
          (await sigValid(parsed.payloadSegment, parsed.sigBytes))) {
        cached = { fetchedAt: now, updated: parsed.payload.updated, revoked: parsed.payload.revoked };
        try { store && store.setItem(CACHE_KEY, JSON.stringify(cached)); } catch { /* storage full/blocked */ }
      }
    } catch { /* offline or bad response — fall back to cache */ }
    finally { clearTimeout(timer); }
  }
  return (cached && cached.revoked) || [];
}

export async function verifyLicence(keyString, { now = Date.now(), checkRevocation = true, fetchImpl, storage } = {}) {
  const parsed = parseToken(keyString, KEY_PREFIX);
  if (!parsed.ok) return { valid: false, reason: parsed.reason, payload: null };
  if (typeof parsed.payload.name !== 'string') return { valid: false, reason: 'malformed', payload: null };

  if (!(await sigValid(parsed.payloadSegment, parsed.sigBytes))) {
    return { valid: false, reason: 'bad-signature', payload: null };
  }
  const p = parsed.payload;

  // Product gate: this app's own product unlocks it; so do two universal
  // products — 'all' (the owner's master key) and 'trial' (a time-limited
  // cross-app trial). A key for another app — or a legacy key with no product
  // field — never unlocks this app.
  if (p.product !== PRODUCT && p.product !== 'all' && p.product !== 'trial') return { valid: false, reason: 'wrong-product', payload: p };

  if (p.expires != null) {
    const exp = Date.parse(p.expires);
    if (Number.isNaN(exp)) return { valid: false, reason: 'malformed', payload: p };
    if (now > exp) return { valid: false, reason: 'expired', payload: p };
  }

  if (checkRevocation && p.jti) {
    const revoked = await revokedJtis({ now, fetchImpl, storage });
    if (revoked.includes(p.jti)) return { valid: false, reason: 'revoked', payload: p };
  }

  return { valid: true, reason: null, payload: p };
}
